version: '3.9'

networks:
  readme:
    name: blog

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    container_name: nginx
    depends_on:
      - php
      - mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      - . :/var/www/html
    networks:
      - readme


  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - . :/var/www/html
    networks:
      - readme

  mysql:
    image: mysql:5.7.33
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: readmedb
      MYSQL_USER: readme
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    restart: always
    networks:
      - readme



