version: '3.9'

networks:
  blog:
    name: blog

services:
  app:
    build: .
    ports:
      - 80:80
    container_name: app
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    networks:
      - blog

  mysql:
    image: mysql:5.7.33
    container_name: data
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_USER: blog
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - blog

